### ISSUE TITLE
invisible text (selected status)

### ISSUE THREAD

**Issue by matteogamba** [transferwise/tw-currency-select#13] opened 2016-02-07 01:18 UTC
When searching for a currency (e.g. INR), if a match is found, the background color = font color -> you can't read the text.

<img width="541" alt="currency selector" src="https://cloud.githubusercontent.com/assets/3117946/12870359/c5539b0e-cd38-11e5-8478-cff6168a8e11.png">

**Comment by kstam** [comment] 2016-02-08 10:27
Can you please describe a bit better how I can reproduce this?

I have just tried in Chrome(version 48.0.2564.97) and Safari(version 9.0.3) and can't reproduce this issue

**Comment by matteogamba** [comment] 2016-02-08 15:06
Chrome Version 48.0.2564.103 (64-bit)
Mac 10.11.3 (15D21)

but also on firefox.

you need to type a currency name (that produces a match), then hover on it
-> bg will become blue, same colour as the font

On Mon, Feb 8, 2016 at 10:27 AM, Kostas Stamatoukos <
notifications@github.com> wrote:

> Can you please describe a bit better how I can reproduce this?
>
> I have just tried in Chrome(version 48.0.2564.97) and Safari(version
> 9.0.3) and can't reproduce this issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/transferwise/tw-currency-select/issues/13#issuecomment-181296173>
> .
>



-- 
*Product Manager*

Join the TransferWise revolution
transferwise.com/matteo
<http://t.yesware.com/tt/5574c2a2bf03b2fefcc2050646df042ecd34c59f/0aaa3edf0b8ba8170d1071c83d0b9da7/e76ecce5d42d99de84f246cd9cb67919/transferwise.com/matteo>


<https://t.yesware.com/tt/5574c2a2bf03b2fefcc2050646df042ecd34c59f/0aaa3edf0b8ba8170d1071c83d0b9da7/748917ecefa63ef6ae0ccf75871919d4/transferwise.com/matteo>
  <matteo@transferwise.com>
<http://t.yesware.com/tt/5574c2a2bf03b2fefcc2050646df042ecd34c59f/0aaa3edf0b8ba8170d1071c83d0b9da7/b970a99e4eb54f5c76fb04c5b3d36c47/twitter.com/transferwise>

<https://t.yesware.com/tt/5574c2a2bf03b2fefcc2050646df042ecd34c59f/0aaa3edf0b8ba8170d1071c83d0b9da7/b3ed55f6a58feb51b909553676f5537f/www.linkedin.com/company/transferwise>

**Comment by kstam** [comment] 2016-02-09 00:20
@matteogamba This should be fixed in the latest release 0.0.16

**Closed** 2016-02-09 00:21 UTC
